spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kezikovboris
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update